server:
  port: 8081
info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
spring:
  application:
    name: notary-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.5:3306/notarization?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
    healthcheck:
      enabled: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
