## spring cloud eureka 注册服务中心配置
server:
  port: 1111
eureka:
  instance:
    hostname: www.notary.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.60
